Virtual Memory Manager: include/initialization/init.h File Reference
init.h File Reference
#include <windows.h>
#include "../variables/structures.h"
Functions
BOOL GetPrivilege (VOID)
VOID init_virtual_memory (VOID)
ULONG64 getMaxFrameNumber (VOID)
BOOL initVA (VOID)
VOID initializePageTableLocks (VOID)
VOID init_pfns (VOID)
BOOL getPhysicalPages (VOID)
VOID init_lists (VOID)
VOID init_free_list (VOID)
VOID init_list_head (pListHead head)
VOID init_num_open_slots (VOID)
VOID init_disk_active (VOID)
PVOID init_memory (ULONG64 numBytes)
VOID init_pageTable (VOID)
VOID init_pte_regions (VOID)
VOID init_disk (VOID)
HANDLE CreateSharedMemorySection (VOID)
Variables
volatile ULONG64 pageWaits
volatile ULONG64 totalTimeWaiting
Function Documentation
CreateSharedMemorySection()
HANDLE CreateSharedMemorySection (VOID)
Definition at line 143 of file init.c.
{
    HANDLE section;
    MEM_EXTENDED_PARAMETER parameter = { 0 };
    // Create an AWE section. Later we deposit pages into it and/or return them.
    parameter.Type = MemSectionExtendedParameterUserPhysicalFlags;
    parameter.ULong = 0;
    section = CreateFileMapping2(INVALID_HANDLE_VALUE,
                                 NULL,
                                 SECTION_MAP_READ | SECTION_MAP_WRITE,
                                 PAGE_READWRITE,
                                 SEC_RESERVE,
                                 0,
                                 NULL,
                                 &parameter,
                                 1);
    return section;
}
Referenced by getPhysicalPages().
getMaxFrameNumber()
ULONG64 getMaxFrameNumber (VOID)
Definition at line 472 of file init.c.
{
    ULONG64 maxFrameNumber;
    maxFrameNumber = 0;
    ULONG64 i;
    for (i = 0; i < NUMBER_OF_PHYSICAL_PAGES; ++i) {
        maxFrameNumber = max(maxFrameNumber, physical_page_numbers[i]);
    }
    return maxFrameNumber;
}
References NUMBER_OF_PHYSICAL_PAGES, and physical_page_numbers.
Referenced by init_pfns().
getPhysicalPages()
BOOL getPhysicalPages (VOID)
Definition at line 354 of file init.c.
{
    BOOL allocated;
    BOOL privilege;
    // Allocate the physical pages that we will be managing.
    // First acquire privilege to do this since physical page control
    // is typically something the operating system reserves the sole
    // right to do.
    privilege = GetPrivilege();
    if (privilege == FALSE) {
        printf("full_virtual_memory_test : could not get privilege\n");
        return FALSE;
    }
    physical_page_handle = CreateSharedMemorySection();
    if (physical_page_handle == NULL) {
        printf("CreateFileMapping2 failed, error %#x\n", GetLastError());
        return FALSE;
    }
    physical_page_count = NUMBER_OF_PHYSICAL_PAGES;
    physical_page_numbers = (PULONG_PTR)malloc(physical_page_count * sizeof(ULONG_PTR));
    if (physical_page_numbers == NULL) {
        printf("full_virtual_memory_test : could not allocate array to hold physical page numbers\n");
        return FALSE;
    }
    allocated = AllocateUserPhysicalPages(physical_page_handle,
                                          &physical_page_count,
                                          physical_page_numbers);
    if (allocated == FALSE) {
        printf("full_virtual_memory_test : could not allocate physical pages\n");
        return FALSE;
    }
    if (physical_page_count != NUMBER_OF_PHYSICAL_PAGES) {
        printf("full_virtual_memory_test : allocated only %llu pages out of %u pages requested\n",
               physical_page_count,
               NUMBER_OF_PHYSICAL_PAGES);
    }
    return TRUE;
}
References CreateSharedMemorySection(), GetPrivilege(), NUMBER_OF_PHYSICAL_PAGES, physical_page_count, physical_page_handle, and physical_page_numbers.
Referenced by init_virtual_memory().
GetPrivilege()
BOOL GetPrivilege (VOID)
Definition at line 92 of file init.c.
                   {
    struct {
        DWORD Count;
        LUID_AND_ATTRIBUTES Privilege[1];
    } Info;
    HANDLE hProcess;
    HANDLE Token;
    BOOL Result;
    // Open the token
    hProcess = GetCurrentProcess();
    Result = OpenProcessToken(hProcess, TOKEN_ADJUST_PRIVILEGES, &Token);
    if (Result == FALSE) {
        printf("Cannot open process token.\n");
        return FALSE;
    }
    // Enable the privilege
    Info.Count = 1;
    Info.Privilege[0].Attributes = SE_PRIVILEGE_ENABLED;
    // Get the LUID
    Result = LookupPrivilegeValue(NULL, SE_LOCK_MEMORY_NAME, &(Info.Privilege[0].Luid));
    if (Result == FALSE) {
        printf("Cannot get privilege\n");
        return FALSE;
    }
    // Adjust the privilege
    Result = AdjustTokenPrivileges(Token, FALSE, (PTOKEN_PRIVILEGES) &Info, 0, NULL, NULL);
    // Check the result
    if (Result == FALSE) {
        printf("Cannot adjust token privileges %u\n", GetLastError());
        return FALSE;
    }
    if (GetLastError() != ERROR_SUCCESS) {
        printf("Cannot enable the SE_LOCK_MEMORY_NAME privilege - check local policy\n");
        return FALSE;
    }
    CloseHandle(Token);
    return TRUE;
}
Referenced by getPhysicalPages().
init_disk()
VOID init_disk (VOID)
Definition at line 196 of file init.c.
                     {
    ULONG64 numBytes;
    // Initialize disk structures
    numBytes = DISK_SIZE_IN_BYTES;
    diskStart = init_memory(numBytes);
    diskEnd = (ULONG64) diskStart + numBytes;
    init_disk_active();
    init_num_open_slots();
}
References DISK_SIZE_IN_BYTES, diskEnd, diskStart, init_disk_active(), init_memory(), and init_num_open_slots().
Referenced by init_virtual_memory().
init_disk_active()
VOID init_disk_active (VOID)
Definition at line 207 of file init.c.
{
    ULONG64 numEntries;
// depending on our disk size check if our bits will go in evenly
#if DISK_SIZE_IN_PAGES % 64 != 0
    numEntries = DISK_SIZE_IN_PAGES / 64 + 1;
#else
    numEntries = DISK_SIZE_IN_PAGES / 64;
#endif
    diskActive = (PULONG64)init_memory(numEntries * sizeof(ULONG64));
    //make the first slot in valid
    diskActive[0] = DISK_ACTIVE;
    //makes it so that the out of bounds portion that exists in our diskMeta data is never accessed
#if DISK_SIZE_IN_PAGES % 64 != 0
    ULONG64 number_of_usable_bits;
    ULONG64 bitMask;
    bitMask = MAXULONG64;
    number_of_usable_bits = (DISK_SIZE_IN_PAGES % 64) - 1;
    bitMask &= (1 << (1 + number_of_usable_bits)) - 1;
    diskActive[numEntries - 1] = ~bitMask;
#endif
    diskActiveEnd = (PULONG64)((ULONG64) diskActive + numEntries);
    diskActiveVa = init_memory(numEntries * sizeof(ULONG64));
}
References DISK_ACTIVE, DISK_SIZE_IN_PAGES, diskActive, diskActiveEnd, diskActiveVa, and init_memory().
Referenced by init_disk().
init_free_list()
VOID init_free_list (VOID)
Definition at line 295 of file init.c.
{
    for (int i = 0; i < NUMBER_OF_FREE_LISTS; ++i) {
        init_list_head(&headFreeLists[i]);
    }
    freeListAddIndex = 0;
    freeListRemoveIndex = 0;
    freeListLength = NUMBER_OF_PHYSICAL_PAGES;
    // Add every page to the free list
    for (int i = 0; i < physical_page_count; ++i) {
        pfn *new_pfn = (pfn*)(pfnStart + physical_page_numbers[i]);
        // Calculate the page-aligned range that contains this pfn structure
         PVOID startPage = (PVOID)ROUND_DOWN_TO_PAGE(new_pfn);
         PVOID endPage = (PVOID)ROUND_UP_TO_PAGE((ULONG_PTR)new_pfn + sizeof(pfn));
        SIZE_T commitSize = (ULONG_PTR)endPage - (ULONG_PTR)startPage;
        // Commit the full page(s) that contain this pfn structure
        if (VirtualAlloc(startPage, commitSize, MEM_COMMIT, PAGE_READWRITE) != startPage) {
            printf("Failed to commit at expected address\n");
        }
        // Now initialize the pfn structure
        memset(new_pfn, 0, sizeof(pfn));
        InitializeCriticalSection(&new_pfn->lock);
        InsertTailList(&headFreeLists[freeListAddIndex], &new_pfn->entry);
        freeListAddIndex++;
        freeListAddIndex %= NUMBER_OF_FREE_LISTS;
    }
}
References pfn::entry, freeListAddIndex, freeListLength, freeListRemoveIndex, headFreeLists, init_list_head(), InsertTailList(), pfn::lock, NUMBER_OF_FREE_LISTS, NUMBER_OF_PHYSICAL_PAGES, pfnStart, physical_page_count, physical_page_numbers, ROUND_DOWN_TO_PAGE, and ROUND_UP_TO_PAGE.
Referenced by init_pfns().
init_list_head()
VOID init_list_head (pListHead head)
Definition at line 339 of file init.c.
{
    head->entry.Flink = &head->entry;
    head->entry.Blink = &head->entry;
    head->length = 0;
    InitializeSRWLock(&head->sharedLock.sharedLock);
    InitializeCriticalSection(&head->page.lock);
#if DBG
    head->sharedLock.numHeldShared = 0;
    head->sharedLock.threadId = -1;
    InitializeListHead(&head->sharedLock.sharedHolders);
    InitializeCriticalSection(&head->sharedLock.debugLock);
#endif
}
References listHead::entry, InitializeListHead(), listHead::length, pfn::lock, listHead::page, listHead::sharedLock, and sharedLock::sharedLock.
Referenced by batchVictimsFromStandByList(), init_free_list(), and init_lists().
init_lists()
VOID init_lists (VOID)
Definition at line 330 of file init.c.
                      {
    init_list_head(&headToBeZeroedList);
    init_list_head(&headStandByList);
    init_list_head(&headModifiedList);
    init_list_head(&headActiveList);
    standByPruningInProgress = false;
}
References headActiveList, headModifiedList, headStandByList, headToBeZeroedList, init_list_head(), and standByPruningInProgress.
Referenced by init_pfns().
init_memory()
PVOID init_memory (ULONG64 numBytes)
Definition at line 484 of file init.c.
{
    PVOID new;
    new = malloc(numBytes);
    if (new == NULL) {
        printf("malloc failed\n");
        exit(1);
    }
    memset(new, 0, numBytes);
    return new;
}
Referenced by init_disk(), init_disk_active(), init_pageTable(), and init_pte_regions().
init_num_open_slots()
VOID init_num_open_slots (VOID)
Definition at line 256 of file init.c.
{
    ULONG64 numBytes;
    numBytes = sizeof(ULONG64) * NUMBER_OF_DISK_DIVISIONS;
    number_of_open_slots = (ULONG64*)malloc(numBytes);
    if (number_of_open_slots == NULL) {
        printf("Failed to allocate memory for number_of_open_slots\n");
        return;
    }
    // if you switch back to more regions, change this back
    for (int i = 0; i < NUMBER_OF_DISK_DIVISIONS; ++i) {
        number_of_open_slots[i] = DISK_SIZE_IN_PAGES - 1;
    }
    // number_of_open_slots[NUMBER_OF_DISK_DIVISIONS - 1] += 2;
    // number_of_open_slots[0] -= 1;
}
References DISK_SIZE_IN_PAGES, NUMBER_OF_DISK_DIVISIONS, and number_of_open_slots.
Referenced by init_disk().
init_pageTable()
VOID init_pageTable (VOID)
Definition at line 186 of file init.c.
{
    ULONG64 numBytes;
    // Initialize the page table
    numBytes = PAGE_TABLE_SIZE_IN_BYTES;
    pageTable = (pte*)init_memory(numBytes);
    init_pte_regions();
}
References init_memory(), init_pte_regions(), PAGE_TABLE_SIZE_IN_BYTES, and pageTable.
Referenced by init_virtual_memory().
init_pfns()
VOID init_pfns (VOID)
Definition at line 277 of file init.c.
                     {
    ULONG64 max = getMaxFrameNumber();
    max += 1;
    pfnStart = VirtualAlloc(NULL,sizeof(pfn)*max,MEM_RESERVE,PAGE_READWRITE);
    if (pfnStart == NULL) {
        printf("Failed to reserve memory for PFN database\n");
        return;
    }
    endPFN = pfnStart + max;
    init_lists();
    init_free_list();
}
References endPFN, getMaxFrameNumber(), init_free_list(), init_lists(), and pfnStart.
Referenced by init_virtual_memory().
init_pte_regions()
VOID init_pte_regions (VOID)
Definition at line 176 of file init.c.
{
    //nptodo add the case where NUMPTES is not divisible by 64
    pteRegionsBase = (PTE_REGION*) init_memory(NUMBER_OF_PTE_REGIONS * sizeof(PTE_REGION));
}
References init_memory(), NUMBER_OF_PTE_REGIONS, and pteRegionsBase.
Referenced by init_pageTable().
init_virtual_memory()
VOID init_virtual_memory (VOID)
Definition at line 166 of file init.c.
{
    getPhysicalPages();
    initVA();
    init_pfns();
    init_pageTable();
    init_disk();
   initThreads();
}
References getPhysicalPages(), init_disk(), init_pageTable(), init_pfns(), initThreads(), and initVA().
Referenced by full_virtual_memory_test().
initializePageTableLocks()
VOID initializePageTableLocks (VOID)
Definition at line 144 of file init_threads.c.
{
    PTE_REGION* p;
    p = pteRegionsBase;
    for (int i = 0; i < NUMBER_OF_PTE_REGIONS; ++i) {
        INITIALIZE_LOCK_DIRECT(p->lock);
        p++;
    }
}
initVA()
BOOL initVA (VOID)
Variable Documentation
pageWaits
volatile ULONG64 pageWaits extern
Definition at line 23 of file init.c.
Referenced by full_virtual_memory_test(), and mapPage().
totalTimeWaiting
volatile ULONG64 totalTimeWaiting extern
Definition at line 24 of file init.c.
Referenced by full_virtual_memory_test(), and mapPage().