Virtual Memory Manager: include/initialization/init_threads.h File Reference
init_threads.h File Reference
#include "../variables/structures.h"
Functions
VOID initThreads (VOID)
VOID createThreads (VOID)
HANDLE createNewThread (LPTHREAD_START_ROUTINE ThreadFunction, PTHREAD_INFO ThreadContext)
VOID initializePageTableLocks (VOID)
VOID initCriticalSections (VOID)
VOID createEvents (VOID)
Function Documentation
createEvents()
VOID createEvents (VOID)
Definition at line 121 of file init_threads.c.
{
    userStartEvent = CreateEvent (NULL, MANUAL_RESET, EVENT_START_OFF, NULL);
    writingStartEvent = CreateEvent(NULL, AUTO_RESET, EVENT_START_OFF, NULL);
    trimmingStartEvent = CreateEvent(NULL, AUTO_RESET, EVENT_START_OFF, NULL);
    writingEndEvent = CreateEvent(NULL, MANUAL_RESET, EVENT_START_OFF, NULL);
    userEndEvent = CreateEvent(NULL, MANUAL_RESET, EVENT_START_OFF, NULL);
    zeroingStartEvent = CreateEvent(NULL, AUTO_RESET, EVENT_START_OFF, NULL);
    systemShutdownEvent = CreateEvent(NULL, MANUAL_RESET, EVENT_START_OFF, NULL);
}
References AUTO_RESET, EVENT_START_OFF, MANUAL_RESET, systemShutdownEvent, trimmingStartEvent, userEndEvent, userStartEvent, writingEndEvent, writingStartEvent, and zeroingStartEvent.
Referenced by initThreads().
createNewThread()
HANDLE createNewThread (LPTHREAD_START_ROUTINE ThreadFunction, PTHREAD_INFO ThreadContext)
Definition at line 156 of file init_threads.c.
{
    HANDLE Handle;
    BOOL ReturnValue;
    Handle = CreateThread(DEFAULT_SECURITY,
                           DEFAULT_STACK_SIZE,
                           ThreadFunction,
                           ThreadContext,
                           DEFAULT_CREATION_FLAGS,
                           &ThreadContext->ThreadId);
    if (Handle == NULL) {
        ReturnValue = GetLastError ();
        printf ("could not create thread %x\n", ReturnValue);
        return NULL;
    }
    return Handle;
}
References DEFAULT_CREATION_FLAGS, DEFAULT_SECURITY, DEFAULT_STACK_SIZE, and PTHREAD_INFO.
Referenced by createThreads().
createThreads()
VOID createThreads (VOID)
Definition at line 27 of file init_threads.c.
{
    PTHREAD_INFO ThreadContext;
    HANDLE Handle;
    THREAD_INFO ThreadInfo[NUMBER_OF_THREADS] = {0};
    THREAD_INFO UserThreadInfo[NUMBER_OF_USER_THREADS] = {0};
    THREAD_INFO TrimmerThreadInfo[NUMBER_OF_TRIMMING_THREADS] = {0};
    THREAD_INFO WriterThreadInfo[NUMBER_OF_WRITING_THREADS] = {0};
    THREAD_INFO ZeroIngThreadInfo[NUMBER_OF_ZEROING_THREADS] = {0};
   // THREAD_INFO SchedulerThreadInfo[NUMBER_OF_SCHEDULING_THREADS] = {0};
    ULONG maxThread = 0;
    ULONG threadHandleArrayOffset;
    for (int i = 0; i < NUMBER_OF_USER_THREADS; ++i) {
        ThreadContext = &UserThreadInfo[i];
        ThreadContext->ThreadNumber = maxThread;
        ThreadContext->TransferVaIndex = 0;
        Handle = createNewThread(testVM, ThreadContext);
        ThreadContext->ThreadHandle = Handle;
        userThreadHandles[i] = Handle;
        maxThread++;
    }
    threadHandleArrayOffset = maxThread;
    for (int i = 0; i < NUMBER_OF_TRIMMING_THREADS; ++i) {
        ThreadContext = &TrimmerThreadInfo[i];
        ThreadContext->ThreadNumber = maxThread;
        Handle = createNewThread(page_trimmer, ThreadContext);
        ThreadContext->ThreadHandle = Handle;
        systemThreadHandles[maxThread-threadHandleArrayOffset] = Handle;
        maxThread++;
    }
    for (int i = 0; i < NUMBER_OF_WRITING_THREADS; ++i) {
        ThreadContext = &WriterThreadInfo[i];
        ThreadContext->ThreadNumber = maxThread;
        Handle = createNewThread(diskWriter,ThreadContext);
        ThreadContext->ThreadHandle = Handle;
        systemThreadHandles[maxThread-threadHandleArrayOffset] = Handle;
        maxThread++;
    }
    for (int i = 0; i < NUMBER_OF_ZEROING_THREADS; ++i) {
        ThreadContext = &ZeroIngThreadInfo[i];
        ThreadContext->ThreadNumber = maxThread;
        Handle = createNewThread(zeroingThread,ThreadContext);
        ThreadContext->ThreadHandle = Handle;
        systemThreadHandles[maxThread-threadHandleArrayOffset] = Handle;
        maxThread++;
    }
    //
    // for (int i = 0; i < NUMBER_OF_SCHEDULING_THREADS; ++i) {
    //     ThreadContext = &SchedulerThreadInfo[i];
    //     ThreadContext->ThreadNumber = maxThread;
    //
    //
    //     Handle = createNewThread(recordProbability,ThreadContext);
    //
    //     ThreadContext->ThreadHandle = Handle;
    //
    //     systemThreadHandles[maxThread-threadHandleArrayOffset] = Handle;
    //
    //     maxThread++;
    // }
}
References createNewThread(), diskWriter(), NUMBER_OF_THREADS, NUMBER_OF_TRIMMING_THREADS, NUMBER_OF_USER_THREADS, NUMBER_OF_WRITING_THREADS, NUMBER_OF_ZEROING_THREADS, page_trimmer(), PTHREAD_INFO, systemThreadHandles, testVM(), THREAD_INFO, TrimmerThreadInfo, userThreadHandles, UserThreadInfo, WriterThreadInfo, and zeroingThread().
Referenced by initThreads().
initCriticalSections()
VOID initCriticalSections (VOID)
Definition at line 131 of file init_threads.c.
{
    INITIALIZE_LOCK(lockDiskActive);
    INITIALIZE_LOCK(lockNumberOfSlots);
    InitializeCriticalSection(&serializeWriterandUser);
//    lockModList = LOCK_FREE;
//    lockToBeZeroedList = LOCK_FREE;
    initializePageTableLocks();
}
References INITIALIZE_LOCK, initializePageTableLocks(), lockDiskActive, lockNumberOfSlots, and serializeWriterandUser.
Referenced by initThreads().
initializePageTableLocks()
VOID initializePageTableLocks (VOID)
Definition at line 144 of file init_threads.c.
{
    PTE_REGION* p;
    p = pteRegionsBase;
    for (int i = 0; i < NUMBER_OF_PTE_REGIONS; ++i) {
        INITIALIZE_LOCK_DIRECT(p->lock);
        p++;
    }
}
References INITIALIZE_LOCK_DIRECT, PTE_REGION::lock, NUMBER_OF_PTE_REGIONS, and pteRegionsBase.
Referenced by initCriticalSections().
initThreads()
VOID initThreads (VOID)
Definition at line 21 of file init_threads.c.
                       {
    createEvents();
    initCriticalSections();
    createThreads();
}
References createEvents(), createThreads(), and initCriticalSections().
Referenced by init_virtual_memory().