Virtual Memory Manager: include/utils/page_utils.h File Reference
page_utils.h File Reference
#include "../variables/structures.h"
Functions
VOID pfnInbounds (pfn *trimmed)
ULONG64 getFrameNumber (pfn *pfn)
pfn * getPFNfromFrameNumber (ULONG64 frameNumber)
VOID removeFromMiddleOfList (pListHead head, pfn *page, PTHREAD_INFO threadInfo)
pfn * RemoveFromHeadofPageList (pListHead head, PTHREAD_INFO threadInfo)
VOID addPageToTail (pListHead head, pfn *page, PTHREAD_INFO threadInfo)
bool removeBatchFromList (pListHead headToRemove, pListHead headToAdd, PTHREAD_INFO threadInfo)
This function removes a batch of pages off of one list onto another instead of removing them one by one.
pfn * RemoveFromHeadWithListLockHeld (pListHead head, PTHREAD_INFO threadInfo)
Function Documentation
addPageToTail()
VOID addPageToTail (pListHead head, pfn * page, PTHREAD_INFO threadInfo)
Definition at line 360 of file page_utils.c.
{
    boolean obtainedPageLocks = FALSE;
    pfn* nextPage;
    acquire_srw_shared(&head->sharedLock);
    for (int i = 0; i < 5; ++i) {
        enterPageLock(&head->page, threadInfo);
        // this page is fine because we hold the heads pseudo page lock and the srw lock shared
        nextPage = container_of(head->entry.Blink, pfn, entry);
        if (&nextPage->entry == &head->entry) {
            nextPage = NULL;
            obtainedPageLocks = TRUE;
            break;
        }
        if (TryEnterCriticalSection(&nextPage->lock) == TRUE) {
            obtainedPageLocks = TRUE;
            break;
        }
        leavePageLock(&head->page, threadInfo);
    }
    if (obtainedPageLocks == FALSE) {
        release_srw_shared(&head->sharedLock);
        acquire_srw_exclusive(&head->sharedLock, threadInfo);
        //check if zero again
        nextPage = container_of(head->entry.Blink, pfn, entry);
        if (&nextPage->entry == &head->entry) {
            nextPage = NULL;
        }
    }
#if DBG
   // validateList(head);
#endif
    if (nextPage == NULL) {
#if !useSharedLock
        ASSERT(head->length == 0);
#endif
        head->entry.Flink = &page->entry;
        head->entry.Blink = &page->entry;
        page->entry.Flink = &head->entry;
        page->entry.Blink = &head->entry;
    } else {
        head->entry.Blink = &page->entry;
        nextPage->entry.Flink = &page->entry;
        page->entry.Blink = &nextPage->entry;
        page->entry.Flink = &head->entry;
    }
    InterlockedIncrement64(&head->length);
#if DBG
  //  validateList(head);
#endif
    if (obtainedPageLocks == TRUE) {
        leavePageLock(&head->page, threadInfo);
        if (nextPage != NULL) {
           leavePageLock(nextPage, threadInfo);
        }
        release_srw_shared(&head->sharedLock);
    } else {
        release_srw_exclusive(&head->sharedLock);
    }
}
References acquire_srw_exclusive(), acquire_srw_shared(), ASSERT, container_of, enterPageLock(), listHead::entry, pfn::entry, leavePageLock(), listHead::length, pfn::lock, listHead::page, PTHREAD_INFO, release_srw_exclusive(), release_srw_shared(), and listHead::sharedLock.
Referenced by addBatchToModifiedList(), addToStandBy(), freeVa(), mapPage(), and rescue_page().
getFrameNumber()
ULONG64 getFrameNumber (pfn * pfn)
Definition at line 19 of file page_utils.c.
{
    return (ULONG64)(pfn - pfnStart);
}
References pfnStart.
Referenced by getPagesFromModifiedList(), mapPage(), mapPageFromFreeList(), mapPageFromStandByList(), and zeroOnePage().
getPFNfromFrameNumber()
pfn * getPFNfromFrameNumber (ULONG64 frameNumber)
Definition at line 23 of file page_utils.c.
{
    return pfnStart + frameNumber;
}
References pfnStart.
Referenced by rescue_page(), unmapActivePage(), and unmapRescuePage().
pfnInbounds()
VOID pfnInbounds (pfn * trimmed)
Definition at line 14 of file page_utils.c.
{
    if (trimmed < pfnStart || trimmed >= endPFN) {
        DebugBreak();
    }
}
References endPFN.
removeBatchFromList()
bool removeBatchFromList (pListHead headToRemove, pListHead headToAdd, PTHREAD_INFO threadInfo)
This function removes a batch of pages off of one list onto another instead of removing them one by one.
Parameters
headToRemove A list head to remove pages from
headToAdd A list head to add the pages removed
threadInfo The info of the calling thread
Return values
True if it was able to remove pages
False if the list to remove from was empty
Postcondition
All the pages added to the local list need to be unlocked
Definition at line 40 of file page_utils.c.
{
    pfn* firstPage;
    pfn* lastPage;
    acquire_srw_shared(&headToRemove->sharedLock);
    enterPageLock(&headToRemove->page, threadInfo);
#if DBG
    validateList(headToRemove);
#endif
    ULONG64 number_of_pages_removed = 0;
    pfn* page;
    InterlockedIncrement64((volatile LONG64 *) &prunecount);
    page = container_of(headToRemove->entry.Flink, pfn, entry);
    // lock all the pages you can up until the threshold
    for (; number_of_pages_removed < NUMBER_OF_PAGES_TO_TRIM_FROM_STAND_BY; number_of_pages_removed++) {
        if (&page->entry == &headToRemove->entry) {
            break;
        }
        enterPageLock(page, threadInfo);
        page = container_of(page->entry.Flink, pfn, entry);
    }
#if DBG
    InterlockedAdd64( (volatile LONG64 *) &pagesremoved,(LONG64) number_of_pages_removed);
#endif
    InterlockedAdd64(&headToRemove->length, (LONG64)
         (0 - number_of_pages_removed));
    // i can edit the flinks and blinks here because all the pages have been lock
    //
    if (number_of_pages_removed != 0) {
        firstPage = container_of(headToRemove->entry.Flink, pfn, entry);
        lastPage = container_of(page->entry.Blink, pfn, entry);
        headToAdd->entry.Flink = &firstPage->entry;
        headToAdd->entry.Blink = &lastPage->entry;
        firstPage->entry.Blink = &headToAdd->entry;
        lastPage->entry.Flink = &headToAdd->entry;
        headToAdd->length = number_of_pages_removed;
        headToRemove->entry.Flink = &page->entry;
        if (&headToRemove->entry == &page->entry) {
            headToRemove->entry.Blink = &headToRemove->entry;
        }
    }
#if DBG
    validateList(headToRemove);
    validateList(headToAdd);
#endif
    leavePageLock(&headToRemove->page, threadInfo);
    release_srw_shared(&headToRemove->sharedLock);
    if (number_of_pages_removed == 0) {
        return LIST_IS_EMPTY;
    }
    return !LIST_IS_EMPTY;
}
References acquire_srw_shared(), container_of, enterPageLock(), listHead::entry, pfn::entry, leavePageLock(), listHead::length, LIST_IS_EMPTY, NUMBER_OF_PAGES_TO_TRIM_FROM_STAND_BY, listHead::page, pagesremoved, prunecount, PTHREAD_INFO, release_srw_shared(), listHead::sharedLock, and validateList().
Referenced by batchVictimsFromStandByList().
RemoveFromHeadofPageList()
pfn * RemoveFromHeadofPageList (pListHead head, PTHREAD_INFO threadInfo)
Definition at line 219 of file page_utils.c.
{
    pfn* pageToRemove;
    pfn* flinkOfPageToRemove;
    boolean obtainedPageLocks;
    obtainedPageLocks = FALSE;
    acquire_srw_shared(&head->sharedLock);
    for (int i = 0; i < 5; ++i) {
        enterPageLock(&head->page, threadInfo);
        pageToRemove = container_of(head->entry.Flink, pfn, entry);
        if (&pageToRemove->entry == &head->entry) {
            leavePageLock(&head->page, threadInfo);
            release_srw_shared(&head->sharedLock);
            return LIST_IS_EMPTY;
        }
        if (TryEnterCriticalSection(&pageToRemove->lock) == FALSE) {
            leavePageLock(&head->page, threadInfo);
            continue;
        }
        // this is safe only because I hold the neighbors pagelock
        flinkOfPageToRemove = container_of(pageToRemove->entry.Flink, pfn, entry);
        // if the list has one entry do not double acquire the listhead pagelock
        if (&flinkOfPageToRemove->entry == &head->entry) {
            flinkOfPageToRemove = NULL;
            obtainedPageLocks = TRUE;
            break;
        }
        if (TryEnterCriticalSection(&flinkOfPageToRemove->lock) == TRUE) {
            obtainedPageLocks = TRUE;
            break;
        }
        leavePageLock(pageToRemove, threadInfo);
        leavePageLock(&head->page, threadInfo);
    }
    if (obtainedPageLocks == FALSE) {
        release_srw_shared(&head->sharedLock);
        // keep trying to acquire the page lock then the list lock exclusive to maintain our order
        while (TRUE) {
            pageToRemove = container_of(head->entry.Flink, pfn, entry);
            if (&pageToRemove->entry == &head->entry) {
                return LIST_IS_EMPTY;
            }
            enterPageLock(pageToRemove, threadInfo);
            acquire_srw_exclusive(&head->sharedLock, threadInfo);
            if (&pageToRemove->entry == head->entry.Flink) {
                break;
            }
//fggf
            release_srw_exclusive(&head->sharedLock);
            leavePageLock(pageToRemove, threadInfo);
        }
        flinkOfPageToRemove = container_of(pageToRemove->entry.Flink, pfn, entry);
        if (&flinkOfPageToRemove->entry == &head->entry) {
           flinkOfPageToRemove = NULL;
        }
    }
    ASSERT(pageToRemove != NULL);
#if DBG
   // validateList(head);
#endif
    LIST_ENTRY* ListHead = &head->entry;
    LIST_ENTRY* Entry = &pageToRemove->entry;
    if (flinkOfPageToRemove == NULL) {
        ListHead->Flink = ListHead;
        ListHead->Blink = ListHead;
    } else {
        LIST_ENTRY* Flink = &flinkOfPageToRemove->entry;
        ListHead->Flink = Flink;
        Flink->Blink = ListHead;
    }
    InterlockedDecrement64(&head->length);
#if DBG
   // validateList(head);
#endif
    if (obtainedPageLocks == TRUE) {
        ASSERT(Entry != ListHead)
       leavePageLock(&head->page, threadInfo);
        if (flinkOfPageToRemove != NULL) {
            LeaveCriticalSection(&flinkOfPageToRemove->lock);
        }
        release_srw_shared(&head->sharedLock);
    } else {
        release_srw_exclusive(&head->sharedLock);
    }
    ASSERT((ULONG64)head->page.lock.OwningThread != threadInfo->ThreadId);
    // leave with page lock held
    return pageToRemove;
}
References acquire_srw_exclusive(), acquire_srw_shared(), ASSERT, container_of, enterPageLock(), listHead::entry, pfn::entry, leavePageLock(), listHead::length, LIST_IS_EMPTY, pfn::lock, listHead::page, PTHREAD_INFO, release_srw_exclusive(), release_srw_shared(), and listHead::sharedLock.
Referenced by getActivePage(), getPagesFromModifiedList(), and getVictimFromStandByList().
RemoveFromHeadWithListLockHeld()
pfn * RemoveFromHeadWithListLockHeld (pListHead head, PTHREAD_INFO threadInfo)
Definition at line 460 of file page_utils.c.
{
    pfn* pageToRemove;
    pfn* flinkOfPageToRemove;
    boolean obtainedPageLocks;
    boolean holdingSharedLock;
    holdingSharedLock = TRUE;
    obtainedPageLocks = FALSE;
    acquire_srw_shared(&head->sharedLock);
    for (int i = 0; i < 5; ++i) {
        pageToRemove = container_of(head->entry.Flink, pfn, entry);
        if (&pageToRemove->entry == &head->entry) {
            release_srw_shared(&head->sharedLock);
            return LIST_IS_EMPTY;
        }
        if (TryEnterCriticalSection(&pageToRemove->lock) == FALSE) {
            continue;
        }
        // this is safe only because I hold the neighbors pagelock
        flinkOfPageToRemove = container_of(pageToRemove->entry.Flink, pfn, entry);
        // if the list has one entry do not double acquire the listhead pagelock
        if (&flinkOfPageToRemove->entry == &head->entry) {
            flinkOfPageToRemove = NULL;
            obtainedPageLocks = TRUE;
            break;
        }
        if (TryEnterCriticalSection(&flinkOfPageToRemove->lock) == TRUE) {
            obtainedPageLocks = TRUE;
            break;
        }
        leavePageLock(pageToRemove, threadInfo);
    }
    if (obtainedPageLocks == FALSE) {
        release_srw_shared(&head->sharedLock);
        holdingSharedLock = FALSE;
        // keep trying to acquire the page lock then the list lock exclusive to maintain our order
        while (TRUE) {
            pageToRemove = container_of(head->entry.Flink, pfn, entry);
            if (&pageToRemove->entry == &head->entry) {
                return LIST_IS_EMPTY;
            }
            enterPageLock(pageToRemove, threadInfo);
            acquire_srw_exclusive(&head->sharedLock, threadInfo);
            if (&pageToRemove->entry == head->entry.Flink) {
                break;
            }
//fggf
            release_srw_exclusive(&head->sharedLock);
            leavePageLock(pageToRemove, threadInfo);
        }
        flinkOfPageToRemove = container_of(pageToRemove->entry.Flink, pfn, entry);
        if (&flinkOfPageToRemove->entry == &head->entry) {
           flinkOfPageToRemove = NULL;
        }
    }
    ASSERT(pageToRemove != NULL);
#if DBG
   // validateList(head);
#endif
    LIST_ENTRY* ListHead = &head->entry;
    LIST_ENTRY* Entry = &pageToRemove->entry;
    if (flinkOfPageToRemove == NULL) {
        ListHead->Flink = ListHead;
        ListHead->Blink = ListHead;
    } else {
        LIST_ENTRY* Flink = &flinkOfPageToRemove->entry;
        ListHead->Flink = Flink;
        Flink->Blink = ListHead;
    }
    InterlockedDecrement64(&head->length);
#if DBG
   // validateList(head);
#endif
    if (obtainedPageLocks == TRUE) {
        ASSERT(Entry != ListHead)
        if (flinkOfPageToRemove != NULL) {
            LeaveCriticalSection(&flinkOfPageToRemove->lock);
        }
        release_srw_shared(&head->sharedLock);
    } else {
        release_srw_exclusive(&head->sharedLock);
    }
    ASSERT((ULONG64)head->page.lock.OwningThread != threadInfo->ThreadId);
    // leave with page lock held
    return pageToRemove;
}
References acquire_srw_exclusive(), acquire_srw_shared(), ASSERT, container_of, enterPageLock(), listHead::entry, pfn::entry, leavePageLock(), listHead::length, LIST_IS_EMPTY, pfn::lock, listHead::page, PTHREAD_INFO, release_srw_exclusive(), release_srw_shared(), and listHead::sharedLock.
removeFromMiddleOfList()
VOID removeFromMiddleOfList (pListHead head, pfn * page, PTHREAD_INFO threadInfo)
Definition at line 122 of file page_utils.c.
{
    pfn* Flink;
    pfn* Blink;
    boolean obtainedPageLocks;
    obtainedPageLocks = FALSE;
    acquire_srw_shared(&head->sharedLock);
    for (int i = 0; i < 5; ++i) {
        // reaching into the neighbors is safe because we have the pagelock
        Flink = container_of(page->entry.Flink, pfn, entry);
        Blink = container_of(page->entry.Blink, pfn, entry);
        if (TryEnterCriticalSection(&Flink->lock) == TRUE) {
            // set blink to null if there is only one page prevents double acquisitions
            if (Flink == Blink) {
                Blink = NULL;
                obtainedPageLocks = TRUE;
                break;
            }
            if (TryEnterCriticalSection(&Blink->lock) == TRUE) {
                obtainedPageLocks = TRUE;
                break;
            }
            leavePageLock(Flink, threadInfo);
        }
    }
    if (obtainedPageLocks == FALSE) {
        release_srw_shared(&head->sharedLock);
        acquire_srw_exclusive(&head->sharedLock, threadInfo);
        // we need to recalculate these because they could have changed inbetween the locks
        // another thread that acquires exclusively could have changed our page
        Flink = container_of(page->entry.Flink, pfn, entry);
        Blink = container_of(page->entry.Blink, pfn, entry);
    }
#if DBG
 //   validateList(head);
    ASSERT(Flink->entry.Blink == &page->entry)
    ASSERT(Blink->entry.Flink == &page->entry)
#endif
    if (Blink == NULL) {
        ASSERT(head->length == 0)
        head->entry.Flink = &head->entry;
        head->entry.Blink = &head->entry;
    } else {
        ASSERT(head->length > 0)
        LIST_ENTRY* prevEntry = &Blink->entry;
        LIST_ENTRY* nextEntry = &Flink->entry;
        prevEntry->Flink = nextEntry;
        nextEntry->Blink = prevEntry;
    }
    InterlockedDecrement64(&head->length);
#if DBG
  //  validateList(head);
#endif
    if (obtainedPageLocks == TRUE) {
        leavePageLock(Flink, threadInfo);
        if (Blink != NULL) {
            leavePageLock(Blink, threadInfo);
        }
        release_srw_shared(&head->sharedLock);
    } else {
        release_srw_exclusive(&head->sharedLock);
    }
    // we must still hold the pagelock other wise a concurrent operation on the same page would corrupt data
}
References acquire_srw_exclusive(), acquire_srw_shared(), ASSERT, container_of, listHead::entry, pfn::entry, leavePageLock(), listHead::length, pfn::lock, PTHREAD_INFO, release_srw_exclusive(), release_srw_shared(), and listHead::sharedLock.
Referenced by rescue_page(), unmapActivePage(), and unmapRescuePage().