Virtual Memory Manager: include/utils/pte_utils.h File Reference
pte_utils.h File Reference
#include "../variables/structures.h"
Functions
pte * va_to_pte (ULONG64 va)
PVOID pte_to_va (pte *pte)
PCRITICAL_SECTION getPageTableLock (pte *pte)
BOOL isVaValid (ULONG64 va)
PTE_REGION * getPTERegion (pte *pte)
Function Documentation
getPageTableLock()
PCRITICAL_SECTION getPageTableLock (pte * pte)
getPTERegion()
PTE_REGION * getPTERegion (pte * pte)
Definition at line 27 of file pte_utils.c.
{
    ULONG64 pageTableIndex = (pte - pageTable);
    ULONG64 index = pageTableIndex / NUMBER_OF_PTES_PER_REGION;
    return  pteRegionsBase + index;
}
References NUMBER_OF_PTES_PER_REGION, pageTable, and pteRegionsBase.
Referenced by freeVa(), isNextPageInSameRegion(), page_trimmer(), pageFault(), and recordAccess().
isVaValid()
BOOL isVaValid (ULONG64 va)
Definition at line 23 of file pte_utils.c.
{
    return (va >= (ULONG64) vaStart) && (va <= (ULONG64) vaEnd);
}
References vaEnd, and vaStart.
Referenced by freeVa(), and pageFault().
pte_to_va()
PVOID pte_to_va (pte * pte)
Definition at line 17 of file pte_utils.c.
                    {
    ULONG64 index = (pte - pageTable);
    return (PVOID)((index * PAGE_SIZE) + (ULONG_PTR) vaStart);
}
References PAGE_SIZE, pageTable, and vaStart.
Referenced by page_trimmer(), and unmapActivePage().
va_to_pte()
pte * va_to_pte (ULONG64 va)
Definition at line 10 of file pte_utils.c.
                      {
    ULONG64 index = ((ULONG_PTR)va - (ULONG_PTR) vaStart)/PAGE_SIZE;
    pte* pte = pageTable + index;
    return pte;
}
References PAGE_SIZE, pageTable, and vaStart.
Referenced by freeVa(), pageFault(), and recordAccess().