Virtual Memory Manager: src/utils/thread_utils.c File Reference
thread_utils.c File Reference
#include "../../include/utils/thread_utils.h"
#include <stdio.h>
#include "../../include/variables/structures.h"
#include "variables/globals.h"
Functions
VOID validateList (pListHead head)
void acquireLock (PULONG64 lock)
void releaseLock (PULONG64 lock)
BOOL tryAcquireLock (PULONG64 lock)
VOID acquire_srw_shared (sharedLock *lock)
VOID release_srw_shared (sharedLock *lock)
VOID acquire_srw_exclusive (sharedLock *lock, PTHREAD_INFO info)
VOID release_srw_exclusive (sharedLock *lock)
VOID enterPageLock (pfn *page, PTHREAD_INFO info)
VOID leavePageLock (pfn *page, PTHREAD_INFO info)
Function Documentation
acquire_srw_exclusive()
VOID acquire_srw_exclusive (sharedLock * lock, PTHREAD_INFO info)
Definition at line 161 of file thread_utils.c.
{
#if DBG
    debug_acquire_srw_exclusive(lock, info);
#else
    AcquireSRWLockExclusive(&lock->sharedLock);
#endif
}
References PTHREAD_INFO, and sharedLock::sharedLock.
Referenced by addPageToTail(), diskWriter(), RemoveFromHeadofPageList(), RemoveFromHeadWithListLockHeld(), and removeFromMiddleOfList().
acquire_srw_shared()
VOID acquire_srw_shared (sharedLock * lock)
Definition at line 145 of file thread_utils.c.
{
#if DBG
    debug_acquire_srw_shared(lock, "unknown", 0);
#else
    AcquireSRWLockShared(&lock->sharedLock);
#endif
}
References sharedLock::sharedLock.
Referenced by addPageToTail(), removeBatchFromList(), RemoveFromHeadofPageList(), RemoveFromHeadWithListLockHeld(), and removeFromMiddleOfList().
acquireLock()
void acquireLock (PULONG64 lock)
Definition at line 115 of file thread_utils.c.
{
    ULONG64 oldValueComparator;
    while (TRUE) {
        oldValueComparator =  InterlockedCompareExchange((volatile LONG *) lock, LOCK_HELD, LOCK_FREE);
        if (oldValueComparator == LOCK_FREE) {
            break;
        }
    }
}
References LOCK_FREE, and LOCK_HELD.
enterPageLock()
VOID enterPageLock (pfn * page, PTHREAD_INFO info)
Definition at line 247 of file thread_utils.c.
{
    ASSERT(info->ThreadId != (ULONG64) page->lock.OwningThread)
    //ASSERT((ULONG64) page->lock.DebugInfo == MAXULONG_PTR)
    EnterCriticalSection(&page->lock);
    //ASSERT((ULONG64) page->lock.DebugInfo == MAXULONG_PTR)
    ASSERT(info->ThreadId == (ULONG64) page->lock.OwningThread)
}
References ASSERT, pfn::lock, and PTHREAD_INFO.
Referenced by addBatchToModifiedList(), addPageToTail(), addToStandBy(), getPageFromFreeList(), isNextPageInSameRegion(), mapPage(), removeBatchFromList(), RemoveFromHeadofPageList(), RemoveFromHeadWithListLockHeld(), rescue_page(), unmapActivePage(), and unmapRescuePage().
leavePageLock()
VOID leavePageLock (pfn * page, PTHREAD_INFO info)
Definition at line 257 of file thread_utils.c.
{
    ASSERT(info->ThreadId == (ULONG64) page->lock.OwningThread)
    //ASSERT((ULONG64) page->lock.DebugInfo == MAXULONG_PTR)
    LeaveCriticalSection(&page->lock);
}
References ASSERT, pfn::lock, and PTHREAD_INFO.
Referenced by addBatchToModifiedList(), addPageToFreeList(), addPageToTail(), addToStandBy(), batchVictimsFromStandByList(), freeVa(), getActivePage(), getPagesFromModifiedList(), getVictimFromStandByList(), isNextPageInSameRegion(), mapPage(), mapPageFromFreeList(), removeBatchFromList(), RemoveFromHeadofPageList(), RemoveFromHeadWithListLockHeld(), removeFromMiddleOfList(), rescue_page(), and unmapRescuePage().
release_srw_exclusive()
VOID release_srw_exclusive (sharedLock * lock)
Definition at line 169 of file thread_utils.c.
{
#if DBG
    debug_release_srw_exclusive(lock);
#else
    ReleaseSRWLockExclusive(&lock->sharedLock);
#endif
}
References sharedLock::sharedLock.
Referenced by addPageToTail(), diskWriter(), RemoveFromHeadofPageList(), RemoveFromHeadWithListLockHeld(), and removeFromMiddleOfList().
release_srw_shared()
VOID release_srw_shared (sharedLock * lock)
Definition at line 153 of file thread_utils.c.
{
#if DBG
    debug_release_srw_shared(lock, "unknown", 0);
#else
    ReleaseSRWLockShared(&lock->sharedLock);
#endif
}
References sharedLock::sharedLock.
Referenced by addPageToTail(), removeBatchFromList(), RemoveFromHeadofPageList(), RemoveFromHeadWithListLockHeld(), and removeFromMiddleOfList().
releaseLock()
void releaseLock (PULONG64 lock)
Definition at line 129 of file thread_utils.c.
{
    InterlockedExchange((volatile LONG *) lock, LOCK_FREE);
}
References LOCK_FREE.
tryAcquireLock()
BOOL tryAcquireLock (PULONG64 lock)
Definition at line 133 of file thread_utils.c.
{
    ULONG64 oldValue;
    oldValue =  InterlockedCompareExchange( (volatile LONG *) lock, LOCK_HELD, LOCK_FREE);
    if (oldValue == LOCK_FREE) {
        return FALSE;
    }
    return TRUE;
}
References LOCK_FREE, and LOCK_HELD.
validateList()
VOID validateList (pListHead head)
Definition at line 46 of file thread_utils.c.
{
    LIST_ENTRY* currentEntry;
    ULONG64 forwardLength = 0;
    ULONG64 backwardLength = 0;
    const ULONG64 MAX_EXPECTED_LENGTH = NUMBER_OF_PHYSICAL_PAGES + 10; // Safety limit
    // Check empty list case
    if (head->length == 0) {
        ASSERT (head->entry.Blink == &head->entry && head->entry.Flink == &head->entry);
        return;
    }
    // Validate forward traversal with cycle detection
    currentEntry = head->entry.Flink;
    while (currentEntry != &head->entry && forwardLength < MAX_EXPECTED_LENGTH) {
        // Check for cross-list corruption
        ASSERT(currentEntry != &headModifiedList.entry &&
               currentEntry != &headStandByList.entry &&
               currentEntry != &headActiveList.entry &&
              // currentEntry != &headFreeList.entry &&
               currentEntry != &headToBeZeroedList.entry);
        // Validate bidirectional linking
        if (currentEntry->Blink->Flink != currentEntry) {
            ASSERT(FALSE); // Broken bidirectional link
            return;
        }
        if (currentEntry->Flink->Blink != currentEntry) {
            ASSERT(FALSE); // Broken bidirectional link
            return;
        }
        currentEntry = currentEntry->Flink;
        forwardLength++;
    }
    // Check for infinite loop
    if (forwardLength >= MAX_EXPECTED_LENGTH) {
        ASSERT(FALSE); // Possible infinite loop detected
        return ;
    }
    // Validate backward traversal
    currentEntry = head->entry.Blink;
    while (currentEntry != &head->entry && backwardLength < MAX_EXPECTED_LENGTH) {
        if (currentEntry->Blink->Flink != currentEntry) {
            ASSERT(FALSE); // Broken bidirectional link
            return;
        }
        if (currentEntry->Flink->Blink != currentEntry) {
            ASSERT(FALSE); // Broken bidirectional link
            return;
        }
        currentEntry = currentEntry->Blink;
        backwardLength++;
    }
    // Verify all lengths match
    BOOL valid = (forwardLength == backwardLength && forwardLength == head->length);
    ASSERT(valid);
    return;
}
References ASSERT, listHead::entry, headActiveList, headModifiedList, headStandByList, headToBeZeroedList, listHead::length, and NUMBER_OF_PHYSICAL_PAGES.
Referenced by addPageToFreeList(), batchVictimsFromStandByList(), getPageFromFreeList(), and removeBatchFromList().