Virtual Memory Manager: src/threads/trimmer_thread.c File Reference
trimmer_thread.c File Reference
This file containsa protocal for unmapping active pages and adding them to a modified list.
#include "../../include/threads/trimmer_thread.h"
#include <stdio.h>
#include "../../include/variables/structures.h"
#include "../../include/variables/globals.h"
#include "../../include/variables/macros.h"
#include "../../include/utils/pte_utils.h"
#include "../../include/utils/page_utils.h"
#include "../../include/utils/thread_utils.h"
Functions
DWORD page_trimmer (LPVOID info)
This is the function that deals with unmapping pages.
pfn * getActivePage (PTHREAD_INFO threadContext)
This functions pops a page off the active list and returns it unlocked.
VOID unmapBatch (PULONG64 virtualAddresses, ULONG64 batchSize)
Simple wrapper for a MapUserPhysicalPagesScatter call.
VOID addBatchToModifiedList (pfn **pages, ULONG64 batchSize, PTHREAD_INFO threadContext)
This function adds a batch of pages to the modified list.
BOOL isNextPageInSameRegion (PTE_REGION *region, PTHREAD_INFO info)
This function peeks into the head of the active list and sees if the next page is in the same pte region.
Detailed Description
This file containsa protocal for unmapping active pages and adding them to a modified list.
Author
Noah Persily
Definition in file trimmer_thread.c.
Function Documentation
addBatchToModifiedList()
VOID addBatchToModifiedList (pfn ** pages, ULONG64 batchSize, PTHREAD_INFO threadContext)
This function adds a batch of pages to the modified list.
Parameters
pages An array of pointers to pages.
batchSize The size of the array.
threadContext The thread info of the caller
Definition at line 161 of file trimmer_thread.c.
{
    pfn* page;
    for (int i = 0; i < batchSize; ++i) {
        page = pages[i];
        enterPageLock(page, threadContext);
        addPageToTail(&headModifiedList, page, threadContext);
        leavePageLock(page, threadContext);
    }
}
References addPageToTail(), enterPageLock(), headModifiedList, leavePageLock(), and PTHREAD_INFO.
Referenced by page_trimmer().
getActivePage()
pfn * getActivePage (PTHREAD_INFO threadContext)
This functions pops a page off the active list and returns it unlocked.
Parameters
threadContext The thread info of the caller.
Returns
Returns an active page. If the list is empty, it returns null.
Definition at line 125 of file trimmer_thread.c.
{
    pfn* page;
    page = RemoveFromHeadofPageList(&headActiveList, threadContext);
    if (page == LIST_IS_EMPTY) {
        return NULL;
    }
    leavePageLock(page, threadContext);
    return page;
}
References headActiveList, leavePageLock(), LIST_IS_EMPTY, PTHREAD_INFO, and RemoveFromHeadofPageList().
Referenced by page_trimmer().
isNextPageInSameRegion()
BOOL isNextPageInSameRegion (PTE_REGION * region, PTHREAD_INFO info)
This function peeks into the head of the active list and sees if the next page is in the same pte region.
Parameters
region The page table region struct of the batch that is currently being trimmed.
info The info of the caller.
Returns
Returns true if the next page's corresponding page table entry is in the region passed in.
Definition at line 179 of file trimmer_thread.c.
{
    pfn* nextPage;
    PTE_REGION* nextRegion;
    sharedLock* lock;
    lock = &headActiveList.sharedLock;
    // Peek ahead
    // TODO make this a no fence on the entry
    enterPageLock(&headActiveList.page, info);
    nextPage = container_of(headActiveList.entry.Flink, pfn, entry);
    leavePageLock(&headActiveList.page, info);
    if (&headActiveList.entry == &nextPage->entry) {
        return LIST_IS_EMPTY;
    }
    nextRegion = getPTERegion(nextPage->pte);
    return nextRegion == region;
}
References container_of, enterPageLock(), pfn::entry, getPTERegion(), headActiveList, leavePageLock(), LIST_IS_EMPTY, pfn::pte, and PTHREAD_INFO.
Referenced by page_trimmer().
page_trimmer()
DWORD page_trimmer (LPVOID info)
This is the function that deals with unmapping pages.
It will pop a page off the active list and add it to the modified list. It will batch unmap if the consecutive pages are in the same page table entry region.
Parameters
info A pointer to a thread info struct. Passed in during the function CreateThread
Return values
0 If the program succeeds
Definition at line 29 of file trimmer_thread.c.
{
    ULONG64 BatchIndex;
    BOOL doubleBreak;
    PCRITICAL_SECTION trimmedPageTableLock;
    pfn* page;
    pfn* pages[BATCH_SIZE];
    ULONG64 virtualAddresses[BATCH_SIZE];
    PTE_REGION* region;
    PTHREAD_INFO threadContext;
    threadContext = (PTHREAD_INFO)info;
    HANDLE events[2];
    DWORD returnEvent;
    events[0] = trimmingStartEvent;
    events[1] = systemShutdownEvent;
    while (TRUE) {
        BatchIndex = 0;
        doubleBreak = FALSE;
        trimmedPageTableLock = NULL;
        returnEvent = WaitForMultipleObjects(2, events, FALSE, INFINITE);
        //if the system shutdown event was signaled, exit
        if (returnEvent - WAIT_OBJECT_0 == 1) {
            return 0;
        }
        // while there is still stuff to trim and the arrays are not at capacity
        while (headModifiedList.length < NUMBER_OF_PHYSICAL_PAGES / 4 && BatchIndex < BATCH_SIZE) {
            page = getActivePage(threadContext);
            if (page == NULL) {
                if (BatchIndex == 0) {
                    doubleBreak = TRUE;
                }
                break;
            }
            // if we are not on a streak we need to get a new region a lock the ptes
            if (trimmedPageTableLock == NULL) {
                region = getPTERegion(page->pte);
                trimmedPageTableLock = &region->lock;
                EnterCriticalSection(trimmedPageTableLock);
            } else {
                ASSERT(region == getPTERegion(page->pte))
            }
            virtualAddresses[BatchIndex] = (ULONG64) pte_to_va(page->pte);
            pages[BatchIndex] = page;
            pages[BatchIndex]->pte->transitionFormat.mustBeZero = 0;
            pages[BatchIndex]->pte->transitionFormat.contentsLocation = MODIFIED_LIST;
            BatchIndex++;
            if (isNextPageInSameRegion(region, threadContext) == FALSE) {
                unmapBatch(virtualAddresses, BatchIndex);
                addBatchToModifiedList(pages, BatchIndex,  threadContext);
                LeaveCriticalSection(trimmedPageTableLock);
                // Setting this to null tells the next loop to get a new region
                trimmedPageTableLock = NULL;
                BatchIndex = 0;
            }
        }
        if (doubleBreak == TRUE) {
            SetEvent(writingStartEvent);
            continue;
        }
        if (BatchIndex == 0) {
            SetEvent(writingStartEvent);
            continue;
        }
        //this just handles the last batch
        unmapBatch(virtualAddresses, BatchIndex);
        addBatchToModifiedList(pages, BatchIndex, (PTHREAD_INFO) threadContext);
        LeaveCriticalSection(trimmedPageTableLock);
        //nptodo add a condition around this
        SetEvent(writingStartEvent);
    }
}
References addBatchToModifiedList(), ASSERT, BATCH_SIZE, transitionPte::contentsLocation, getActivePage(), getPTERegion(), headModifiedList, isNextPageInSameRegion(), PTE_REGION::lock, MODIFIED_LIST, transitionPte::mustBeZero, NUMBER_OF_PHYSICAL_PAGES, pfn::pte, pte_to_va(), PTHREAD_INFO, systemShutdownEvent, pte::transitionFormat, trimmingStartEvent, unmapBatch(), and writingStartEvent.
Referenced by createThreads().
unmapBatch()
VOID unmapBatch (PULONG64 virtualAddresses, ULONG64 batchSize)
Simple wrapper for a MapUserPhysicalPagesScatter call.
Parameters
virtualAddresses An array of virtual addresses to unmap.
batchSize The size of the array.
Definition at line 145 of file trimmer_thread.c.
{
    if (MapUserPhysicalPagesScatter((PVOID)virtualAddresses, batchSize, NULL) == FALSE) {
        DebugBreak();
        printf("full_virtual_memory_test : could not unmap VA %p\n", transferVaWriting);
        return;
    }
}
References transferVaWriting.
Referenced by page_trimmer().