Virtual Memory Manager: src/threads/user_thread.c File Reference
user_thread.c File Reference
#include "../../include/threads/user_thread.h"
#include <stdio.h>
#include "../../include/variables/globals.h"
#include "../../include/variables/structures.h"
#include "../../include/variables/macros.h"
#include "../../include/utils/pte_utils.h"
#include "../../include/utils/page_utils.h"
#include "../../include/disk/disk.h"
#include "../../include/utils/thread_utils.h"
#include "initialization/init.h"
Functions
VOID addPageToFreeList (pfn *page, PTHREAD_INFO threadInfo)
Adds a page to any available freelist.
VOID batchVictimsFromStandByList (PTHREAD_INFO threadInfo)
Removes a batch of victims from the standby list and puts them on the free list.
PVOID getThreadMapping (PTHREAD_INFO threadContext)
A function that gets the current transfer virtual address that a thread needs.
VOID freeThreadMapping (PTHREAD_INFO threadContext)
Unmaps the thread's transfer virtual address space if it has all mapped.
BOOL pageFault (PULONG_PTR arbitrary_va, LPVOID threadContext)
This function is the core of the program.
BOOL isRescue (pte *currentPTE)
BOOL rescue_page (ULONG64 arbitrary_va, pte *currentPTE, PTHREAD_INFO threadInfo)
This function will rescue a page table entry that has been unmapped by the trimming thread, but the contents of the virtual page are still on the physical page.
BOOL mapPage (ULONG64 arbitrary_va, pte *currentPTE, LPVOID threadContext, PCRITICAL_SECTION currentPageTableLock)
This function handles the first time a virtual address is accessed, and if a virtual address contents are on disk.
pfn * mapPageFromFreeList (pte *currentPTE, PTHREAD_INFO threadInfo)
This function tries to get a physical page of a free list.
pfn * mapPageFromStandByList (pte *currentPTE, PTHREAD_INFO threadInfo)
This function attempts to take a page from the standby list.
pfn * getVictimFromStandByList (PTHREAD_INFO threadInfo)
This function pops a page off the standby list and updates its pte.
VOID modified_read (pte *currentPTE, ULONG64 frameNumber, PTHREAD_INFO threadContext)
This function reads in the contents of a disk page onto a physical page.
BOOL zeroOnePage (pfn *page, PTHREAD_INFO threadContext)
This function zeroes a physical page.
pfn * getPageFromFreeList (PTHREAD_INFO threadContext)
This function gets a page off of one of the free lists.
Function Documentation
addPageToFreeList()
VOID addPageToFreeList (pfn * page, PTHREAD_INFO threadInfo)
Adds a page to any available freelist.
Parameters
page The page you are inserting into the list
threadInfo The thread info of a caller. It is mainly used for debug functions
Precondition
The page must be locked.
Postcondition
The caller must release the page lock.
Definition at line 47 of file user_thread.c.
{
    ULONG64 localFreeListIndex;
    // Increment the global index which is a guess as to what free list most likely is available and has pages
    localFreeListIndex = InterlockedIncrement(&freeListAddIndex);
    localFreeListIndex %= NUMBER_OF_FREE_LISTS;
    InterlockedIncrement64((volatile LONG64 *)&freeListLength);
    // iterate through the freelists starting at the index calculated above and try to lock it
    while (TRUE) {
        // once you lock a free list insert it at the head
        if (TryEnterCriticalSection(&headFreeLists[localFreeListIndex].page.lock) == TRUE) {
#if DBG
            validateList(&headFreeLists[localFreeListIndex]);
#endif
            InsertHeadList(&headFreeLists[localFreeListIndex], &page->entry );
#if DBG
            validateList(&headFreeLists[localFreeListIndex]);
#endif
            leavePageLock(&headFreeLists[localFreeListIndex].page, threadInfo);
            return;
        }
        // increment and wrap
        localFreeListIndex = (localFreeListIndex + 1) % NUMBER_OF_FREE_LISTS;
    }
}
References pfn::entry, freeListAddIndex, freeListLength, headFreeLists, InsertHeadList(), leavePageLock(), pfn::lock, NUMBER_OF_FREE_LISTS, PTHREAD_INFO, and validateList().
Referenced by addToStandBy(), and batchVictimsFromStandByList().
batchVictimsFromStandByList()
VOID batchVictimsFromStandByList (PTHREAD_INFO threadInfo)
Removes a batch of victims from the standby list and puts them on the free list.
Parameters
threadInfo The thread info of a caller. It is mainly used for debug functions.
Definition at line 89 of file user_thread.c.
{
    listHead localList;
    pfn* page;
    pfn* nextPage;
    init_list_head(&localList);
    // adds pages onto the local list from the standby list but does not update them
    // returns with all the pages locked
    if (removeBatchFromList(&headStandByList, &localList, threadInfo) == LIST_IS_EMPTY) {
        return;
    }
#if DBG
    validateList(&localList);
#endif
    page = container_of(localList.entry.Flink, pfn, entry);
    // For every page on the local list
    while (&page->entry != &localList.entry) {
        // We can do this without a pte lock because the page lock protects it from rescues
        page->pte->transitionFormat.contentsLocation = DISK;
        page->pte->invalidFormat.diskIndex = page->diskIndex;
        // add it to the list and manage locks
        nextPage = container_of(page->entry.Flink, pfn, entry);
        addPageToFreeList(page, threadInfo);
        leavePageLock(page, threadInfo);
        page = nextPage;
    }
}
References addPageToFreeList(), container_of, transitionPte::contentsLocation, DISK, invalidPte::diskIndex, pfn::diskIndex, listHead::entry, pfn::entry, headStandByList, init_list_head(), pte::invalidFormat, leavePageLock(), LIST_IS_EMPTY, pfn::pte, PTHREAD_INFO, removeBatchFromList(), pte::transitionFormat, and validateList().
Referenced by getPageFromFreeList().
freeThreadMapping()
VOID freeThreadMapping (PTHREAD_INFO threadContext)
Unmaps the thread's transfer virtual address space if it has all mapped.
Batching it in this way saves a lot of time spent mapping and flushing.
Parameters
threadContext The thread info of the caller. It is used to index into the correct transfer virtual address space.
Definition at line 149 of file user_thread.c.
{
    // If we are at the end, reset and unmap everything
    if (threadContext->TransferVaIndex == SIZE_OF_TRANSFER_VA_SPACE_IN_PAGES) {
        threadContext->TransferVaIndex = 0;
        if (MapUserPhysicalPages(userThreadTransferVa[threadContext->ThreadNumber], SIZE_OF_TRANSFER_VA_SPACE_IN_PAGES, NULL) == FALSE) {
            DebugBreak();
            printf("full_virtual_memory_test : could not unmap VA %p\n", userThreadTransferVa[threadContext->ThreadNumber]);
            return;
        }
    }
}
References PTHREAD_INFO, SIZE_OF_TRANSFER_VA_SPACE_IN_PAGES, and userThreadTransferVa.
Referenced by modified_read(), and zeroOnePage().
getPageFromFreeList()
pfn * getPageFromFreeList (PTHREAD_INFO threadContext)
This function gets a page off of one of the free lists.
It returns with the page locked.
Parameters
threadContext The thread info of the caller.
Returns
Returns a free page.
Postcondition
The caller must release the page lock of the returned page.
Definition at line 637 of file user_thread.c.
{
    ULONG64 localFreeListIndex;
    PLIST_ENTRY entry;
    pfn* page;
    ULONG64 localTotalFreeListLength;
    boolean pruneInProgress = FALSE;
    boolean gotFreeListLock = FALSE;
    ULONG64 counter;
    counter = 0;
    // Increment global data that approximates what free list should be the most full/least contended
    localFreeListIndex = InterlockedIncrement(&freeListRemoveIndex) % NUMBER_OF_FREE_LISTS;
    // Iterate through the freelists starting at the index calculated above and try to lock it
    while (TRUE) {
        // In our first run through, just try to enter a freelist lock
        if (counter < NUMBER_OF_FREE_LISTS) {
            if (TryEnterCriticalSection(&headFreeLists[localFreeListIndex].page.lock) == TRUE) {
                gotFreeListLock = TRUE;
            }
            // if all of them were empty at the time we checked
        } else if (counter == 2* NUMBER_OF_FREE_LISTS) {
            return LIST_IS_EMPTY;
            // acquire a freelist lock exclusive
        } else {
            EnterCriticalSection(&headFreeLists[localFreeListIndex].page.lock);
            gotFreeListLock = TRUE;
        }
        if (gotFreeListLock) {
#if DBG
        validateList(&headFreeLists[localFreeListIndex]);
#endif
            // now we have a locked page
            entry = RemoveHeadList(&headFreeLists[localFreeListIndex]);
            if (entry == LIST_IS_EMPTY) {
                page = LIST_IS_EMPTY;
            } else {
                page = container_of(entry, pfn, entry);
            }
#if DBG
            validateList(&headFreeLists[localFreeListIndex]);
#endif
            // now that the page is off the list we no longer need to lock the list
            LeaveCriticalSection(&headFreeLists[localFreeListIndex].page.lock);
            if (page == LIST_IS_EMPTY) {
                gotFreeListLock = FALSE;
                counter++;
                localFreeListIndex = (localFreeListIndex + 1) % NUMBER_OF_FREE_LISTS;
                continue;
            } else {
                // The following code calls the standby pruner.
                localTotalFreeListLength = InterlockedDecrement64((volatile LONG64 *) &freeListLength);
               ASSERT(localTotalFreeListLength != MAXULONG64);
                // check to see if we have enough pages on the free list
                if (localTotalFreeListLength <= STAND_BY_TRIM_THRESHOLD) {
                    // if there is not a pruning mission already happening
                    pruneInProgress = InterlockedCompareExchange((volatile LONG *)&standByPruningInProgress, TRUE, FALSE);
                    if (pruneInProgress == FALSE) {
                        batchVictimsFromStandByList(threadContext);
                    }
                    InterlockedExchange(&standByPruningInProgress, FALSE);
                }
                // return a locked page
                enterPageLock(page, threadContext);
                return page;
            }
        }
        // go around in a circle
        localFreeListIndex = (localFreeListIndex + 1) % NUMBER_OF_FREE_LISTS;
        counter++;
    }
}
References ASSERT, batchVictimsFromStandByList(), container_of, enterPageLock(), freeListLength, freeListRemoveIndex, headFreeLists, LIST_IS_EMPTY, pfn::lock, NUMBER_OF_FREE_LISTS, PTHREAD_INFO, RemoveHeadList(), STAND_BY_TRIM_THRESHOLD, standByPruningInProgress, and validateList().
Referenced by mapPageFromFreeList().
getThreadMapping()
PVOID getThreadMapping (PTHREAD_INFO threadContext)
A function that gets the current transfer virtual address that a thread needs.
Parameters
threadContext The thread info of the caller. It is used to update the per thread index into its transfer virtual address space.
Returns
A pointer to a page of unmapped transfer virtual address space.
Definition at line 133 of file user_thread.c.
{
    // Get the current thread's transfer va space
    PVOID currentTransferVa = userThreadTransferVa[threadContext->ThreadNumber];
    // Index into it
    PVOID va = (PVOID) ((ULONG64) currentTransferVa + PAGE_SIZE  * threadContext->TransferVaIndex);
    threadContext->TransferVaIndex += 1;
    ASSERT(threadContext->TransferVaIndex <= SIZE_OF_TRANSFER_VA_SPACE_IN_PAGES);
    return va;
}
References ASSERT, PAGE_SIZE, PTHREAD_INFO, SIZE_OF_TRANSFER_VA_SPACE_IN_PAGES, and userThreadTransferVa.
Referenced by modified_read(), and zeroOnePage().
getVictimFromStandByList()
pfn * getVictimFromStandByList (PTHREAD_INFO threadInfo)
This function pops a page off the standby list and updates its pte.
Important note, it updates the page table entry of the page without holding a page table lock. It can do this because the page table entry's corresponding page lock protects it from being rescued at the same. However, this means that in the rescue or other functions relating to standby pages, the page table entry could be changing.
Parameters
threadInfo The thread info of the caller.
Returns
Return a page from the standby list. If the list is empty return NULL
Definition at line 536 of file user_thread.c.
{
    pfn* page;
    pte local;
    // Exits with page lock held
    page = RemoveFromHeadofPageList(&headStandByList, threadInfo);
    if (page == LIST_IS_EMPTY) {
        return NULL;
    }
    // we can edit the pte without a lock because the page lock protects it
    // if another faulter tries to get this the pagelock will stop it in the rescue
    // if the rescue sees a change in the pte it will redo the fault
    // We have to write no fence here in order to avoid tearing
    local.transitionFormat.contentsLocation = DISK;
    local.invalidFormat.diskIndex = page->diskIndex;
    WriteULong64NoFence(page->pte,  local.entireFormat);
    leavePageLock(page, threadInfo);
    return page;
}
References transitionPte::contentsLocation, DISK, invalidPte::diskIndex, pfn::diskIndex, pte::entireFormat, headStandByList, pte::invalidFormat, leavePageLock(), LIST_IS_EMPTY, pfn::pte, PTHREAD_INFO, RemoveFromHeadofPageList(), and pte::transitionFormat.
Referenced by mapPageFromStandByList().
isRescue()
BOOL isRescue (pte * currentPTE)
Parameters
currentPTE The page table entry of the virtual address that was faulted on.
Returns
It returns true if the currentPTE is signaled as transition.
Precondition
The page table entry must be locked.
Postcondition
The caller must release the lock of the page table entry.
Definition at line 230 of file user_thread.c.
{
    return (currentPTE->transitionFormat.contentsLocation == MODIFIED_LIST) ||
            (currentPTE->transitionFormat.contentsLocation == STAND_BY_LIST);
}
References transitionPte::contentsLocation, MODIFIED_LIST, STAND_BY_LIST, and pte::transitionFormat.
Referenced by freeVa(), pageFault(), and rescue_page().
mapPage()
BOOL mapPage (ULONG64 arbitrary_va, pte * currentPTE, LPVOID threadContext, PCRITICAL_SECTION currentPageTableLock)
This function handles the first time a virtual address is accessed, and if a virtual address contents are on disk.
First this thread will attempt to map from the free list; then it will try to map from standby. If none of those succeed it will wake up the trimmer and wait to redo the fault. If this thread notices that usable pages are getting low, it will wake up the trimmer.
Parameters
arbitrary_va The virtual address being accessed.
currentPTE The page table entry of the virtual address being accessed.
threadContext The thread info of the faulting thread.
currentPageTableLock The lock corresponding to the page table entry
Returns
Returns true if we need to redo the fault, false otherwise.
Precondition
The page table entry must be locked on entry to this function.
Postcondition
The caller must unlock the page table entry.
Definition at line 351 of file user_thread.c.
{
    pfn** page_pointer;
    pfn* page;
    ULONG64 frameNumber;
    PTHREAD_INFO threadInfo;
    threadInfo = (PTHREAD_INFO)threadContext;
    page = NULL;
    // Attempt to get a page from the free list and standby list
    // NULL means the page could not be found
     page = mapPageFromFreeList(currentPTE, threadInfo);
     if (page == NULL) {
         page = mapPageFromStandByList(currentPTE,  threadInfo);
         if (page == NULL) {
            // If we are not able to get a page, start the trimmer and sleep
            LeaveCriticalSection(currentPageTableLock);
            //TODO find a way to resolve the case where it resets writing end event and there is a deadlock
            ResetEvent(writingEndEvent);
            SetEvent(trimmingStartEvent);
            pageWaits++;
            ULONG64 start;
            ULONG64 end;
            start = ReadTimeStampCounter();
#if spinEvents
            spinWhileWaiting();
#else
            WaitForSingleObject(writingEndEvent, INFINITE);
#endif
           end = ReadTimeStampCounter();
            InterlockedAdd64((volatile LONG64 *) &totalTimeWaiting, (LONG64)(end - start));
            EnterCriticalSection(currentPageTableLock);
            return REDO_FAULT;
        }
    }
    // if we seem to be running low on free and standby pages wake the trimmer
    if (((double) (headStandByList.length + ReadULong64NoFence(&freeListLength)) / ((double) NUMBER_OF_PHYSICAL_PAGES )) < .5) {
        SetEvent(trimmingStartEvent);
    }
    frameNumber = getFrameNumber(page);
    //validate the pte and add it to the list
    currentPTE->validFormat.frameNumber = frameNumber;
    currentPTE->validFormat.valid = 1;
    page->pte = currentPTE;
    if (MapUserPhysicalPages((PVOID)arbitrary_va, 1, &frameNumber) == FALSE) {
        DebugBreak();
        printf("full_virtual_memory_test : could not map VA %llu to page %llX\n", arbitrary_va, frameNumber);
        return FALSE;
    }
    enterPageLock(page, threadInfo);
    addPageToTail(&headActiveList, page, threadInfo);
    leavePageLock(page, threadContext);
    return !REDO_FAULT;
}
References addPageToTail(), enterPageLock(), validPte::frameNumber, freeListLength, getFrameNumber(), headActiveList, headStandByList, leavePageLock(), mapPageFromFreeList(), mapPageFromStandByList(), NUMBER_OF_PHYSICAL_PAGES, pageWaits, pfn::pte, PTHREAD_INFO, REDO_FAULT, totalTimeWaiting, trimmingStartEvent, validPte::valid, pte::validFormat, and writingEndEvent.
Referenced by pageFault().
mapPageFromFreeList()
pfn * mapPageFromFreeList (pte * currentPTE, PTHREAD_INFO threadInfo)
This function tries to get a physical page of a free list.
It will also detect if the number of free pages is running low, and take some from the standby list.
Parameters
currentPTE The page table entry of the virtual address that is being faulted on
threadInfo The info about the calling thread.
Returns
Returns a page from a freelist
Return values
Returns null if the list is empty
Precondition
The page table entry must be locked on entry to this function.
Postcondition
The caller must unlock the page table entry.
Definition at line 449 of file user_thread.c.
{
    pfn* page;
    ULONG64 frameNumber;
    // This function acquires the page lock
    page = getPageFromFreeList(threadInfo);
    if (page == LIST_IS_EMPTY) {
        return NULL;
    }
    leavePageLock(page, threadInfo);
    frameNumber = getFrameNumber(page);
    // Zero the page if we are on a first fault, otherwise read from disk
    if (currentPTE->invalidFormat.diskIndex != EMPTY_PTE) {
        modified_read(currentPTE, frameNumber, threadInfo);
    } else {
        zeroOnePage(page, threadInfo);
    }
    return page;
}
References invalidPte::diskIndex, EMPTY_PTE, getFrameNumber(), getPageFromFreeList(), pte::invalidFormat, leavePageLock(), LIST_IS_EMPTY, modified_read(), PTHREAD_INFO, and zeroOnePage().
Referenced by mapPage().
mapPageFromStandByList()
pfn * mapPageFromStandByList (pte * currentPTE, PTHREAD_INFO threadInfo)
This function attempts to take a page from the standby list.
If there is a page to take, this function will update the page's pagetable entry to reflect that it is no longer on standby, but on disk
Parameters
currentPTE The page table entry of the virtual address that is being faulted on
threadInfo The info of the calling thread
Returns
Returns a page from a freelist
Return values
Returns null if the list is empty
Precondition
The page table entry must be locked on entry to this function.
Postcondition
The caller must unlock the page table entry
Definition at line 494 of file user_thread.c.
{
    ULONG64 frameNumber;
    pte entryContents;
    pfn* page;
    entryContents = *currentPTE;
    // All locks pertaining to this page are dealt with in this function. We do not need to lock or unlock it
    page = getVictimFromStandByList(threadInfo);
    if (page == NULL) {
        return NULL;
    }
    frameNumber = getFrameNumber(page);
    // Zero the page if we are on a first fault, otherwise read from disk
    if (entryContents.invalidFormat.diskIndex == EMPTY_PTE) {
        if (!zeroOnePage(page, threadInfo)) {
            DebugBreak();
        }
    } else {
        modified_read(currentPTE, frameNumber, threadInfo);
    }
    return page;
}
References invalidPte::diskIndex, EMPTY_PTE, getFrameNumber(), getVictimFromStandByList(), pte::invalidFormat, modified_read(), PTHREAD_INFO, and zeroOnePage().
Referenced by mapPage().
modified_read()
VOID modified_read (pte * currentPTE, ULONG64 frameNumber, PTHREAD_INFO threadContext)
This function reads in the contents of a disk page onto a physical page.
It uses an interim transfer virtual address to complete this task. Only after the entire transfer space is used, will this function unmap the pages from the transfer virtual address. By having limited unmap calls, a lot of time spent flushing and unmapping is saved.
Parameters
currentPTE The page table entry that contains the disk page we want to read from.
frameNumber The frame to read into.
threadContext The caller's thread info. It is used to determine which transfer virtual page to use
Precondition
The page table entry must be locked on entry to this function.
Postcondition
The caller must unlock the page table entry
Definition at line 577 of file user_thread.c.
{
    ULONG64 diskIndex = currentPTE->invalidFormat.diskIndex;
    ULONG64 diskAddress = (ULONG64) diskStart + diskIndex * PAGE_SIZE;
    PVOID transferVaLocation = getThreadMapping(threadContext);
    if (MapUserPhysicalPages(transferVaLocation, 1, &frameNumber) == FALSE) {
        DebugBreak();
        printf("full_virtual_memory_test : could not map VA %p to page %llX\n", transferVaLocation, frameNumber);
        return;
    }
    memcpy(transferVaLocation, (PVOID) diskAddress, PAGE_SIZE);
    freeThreadMapping(threadContext);
    set_disk_space_free(diskIndex);
}
References invalidPte::diskIndex, diskStart, freeThreadMapping(), getThreadMapping(), pte::invalidFormat, PAGE_SIZE, PTHREAD_INFO, and set_disk_space_free().
Referenced by mapPageFromFreeList(), and mapPageFromStandByList().
pageFault()
BOOL pageFault (PULONG_PTR arbitrary_va, LPVOID threadContext)
This function is the core of the program.
It will culminate in the mapping of a physical page to the passed in virtual address.
Parameters
arbitrary_va The virtual address that is being accessed and faulted on.
threadContext The information about the faulting thread.
Returns
A boolean that determines whether we need to back up and redo the fault.
Definition at line 170 of file user_thread.c.
{
    BOOL returnValue;
    pte* currentPTE;
    pte pteContents;
    PCRITICAL_SECTION currentPageTableLock;
    PTE_REGION* region;
    currentPTE = va_to_pte((ULONG64) arbitrary_va);
    // Checks to see if the user is accessing out of bounds va space
    if (isVaValid((ULONG64) arbitrary_va) == FALSE) {
        DebugBreak();
        printf("invalid va %p\n", arbitrary_va);
    }
    returnValue = !REDO_FAULT;
    region = getPTERegion(currentPTE);
    currentPageTableLock = &region->lock;
    EnterCriticalSection(currentPageTableLock);
    pteContents = *currentPTE;
    // If the page fault was already handled by another thread
    if (pteContents.validFormat.valid != TRUE) {
        // If the pte is in flight
        if (isRescue(currentPTE)) {
            // Determine if the rescue told us to back up or not
            if (rescue_page((ULONG64) arbitrary_va, currentPTE, (PTHREAD_INFO) threadContext) == REDO_FAULT) {
                returnValue = REDO_FAULT;
            }
        } else {
            // If we are on a first fault or a disk read map that page.
            if (mapPage((ULONG64) arbitrary_va, currentPTE, threadContext, currentPageTableLock) == REDO_FAULT) {
                returnValue = REDO_FAULT;
            }
        }
    }
    LeaveCriticalSection(currentPageTableLock);
    return returnValue;
}
References getPTERegion(), isRescue(), isVaValid(), PTE_REGION::lock, mapPage(), PTHREAD_INFO, REDO_FAULT, rescue_page(), va_to_pte(), validPte::valid, and pte::validFormat.
Referenced by testVM().
rescue_page()
BOOL rescue_page (ULONG64 arbitrary_va, pte * currentPTE, PTHREAD_INFO threadInfo)
This function will rescue a page table entry that has been unmapped by the trimming thread, but the contents of the virtual page are still on the physical page.
If the page corresponding to the virtual address is on the modified list, this function just simply removes it from the middle. If the page is on the standby list, this function removes it from the middle of the list and sets the corresponding disk space free. Lastly, If the page is not on any list, but in the process of being written out, just mark it as no longer being written out. The writer will see this and free the corresponding disk space
Parameters
arbitrary_va The virtual address that is faulted on.
currentPTE The page table entry corresponding with the virtual address.
threadInfo The info of the thread that is faulted on.
Returns
Returns true if we need to redo the fault, false otherwise.
Precondition
The page table entry must be locked on entry to this function.
Postcondition
The caller must unlock the page table entry
Definition at line 251 of file user_thread.c.
{
    pfn* page;
    ULONG64 frameNumber;
    pte entryContents;
    // We must read no fence because the pte could be getting cross edited by another faulter who is using it as a victim
    entryContents.entireFormat = ReadULong64NoFence((DWORD64 const volatile *)currentPTE);
    // The following two checks see if the case where a pte is cross edited in the process of victimization occured
    // If before we got our snapshot, the pte was changed to non rescue
    if (!isRescue(currentPTE)){
        return REDO_FAULT;
    }
    frameNumber = entryContents.transitionFormat.frameNumber;
    page = getPFNfromFrameNumber(frameNumber);
    // if our page that we believe our contents is on no longer maps to our copy
    if (page->pte->entireFormat != entryContents.entireFormat) {
        return REDO_FAULT;
    }
    enterPageLock(page, threadInfo);
    // Now that we are in the pagelock we can be sure the pte is not being edited without a lock in our victimization code.
    // Therefore, we can now check the actual pte for the same things as above as opposed to our copy
    if (page->pte != currentPTE) {
        leavePageLock(page, threadInfo);
        return REDO_FAULT;
    }
    if (!isRescue(currentPTE)) {
        leavePageLock(page, threadInfo);
        return REDO_FAULT;
    }
    ASSERT(currentPTE->transitionFormat.frameNumber == frameNumber);
    // If there is a write in progress the page is not on any list
    // We do not know when in the right this is occurring, so we set this variable to signal to the writer to not add this
    // page to the standby list
    // Instead, the writer will free its disk space
    if (page->isBeingWritten == TRUE) {
        page->isBeingWritten = FALSE;
    }
    // If its on standby, remove it and set the disk space free
    else if (currentPTE->transitionFormat.contentsLocation == STAND_BY_LIST) {
        removeFromMiddleOfList(&headStandByList, page, threadInfo);
        set_disk_space_free(page->diskIndex);
    } else {
        // It must be on the modified list now if it was determined to be a rescue but no a write in progress or a standby page
        removeFromMiddleOfList(&headModifiedList,page, threadInfo);
    }
    // we can leave this lock because it is no longer on a list, so no other operations like a list removal but be poking at this page
    // A faulter that is accessing the same region will be stopped by a pagetable lock
    leavePageLock(page, threadInfo);
    if (MapUserPhysicalPages((PVOID)arbitrary_va, 1, &frameNumber) == FALSE) {
        DebugBreak();
        printf("full_virtual_memory_test : could not map VA %p to page %llX\n", (PVOID)arbitrary_va, frameNumber);
        return FALSE;
    }
    currentPTE->validFormat.valid = 1;
    currentPTE->validFormat.transition = UNASSIGNED;
    enterPageLock(page, threadInfo);
    addPageToTail(&headActiveList, page, threadInfo);
    leavePageLock(page, threadInfo);
    return !REDO_FAULT;
}
References addPageToTail(), ASSERT, transitionPte::contentsLocation, pfn::diskIndex, enterPageLock(), pte::entireFormat, transitionPte::frameNumber, getPFNfromFrameNumber(), headActiveList, headModifiedList, headStandByList, pfn::isBeingWritten, isRescue(), leavePageLock(), pfn::pte, PTHREAD_INFO, REDO_FAULT, removeFromMiddleOfList(), set_disk_space_free(), STAND_BY_LIST, validPte::transition, pte::transitionFormat, UNASSIGNED, validPte::valid, and pte::validFormat.
Referenced by pageFault().
zeroOnePage()
BOOL zeroOnePage (pfn * page, PTHREAD_INFO threadContext)
This function zeroes a physical page.
It uses an interim transfer virtual address to complete this task. Only after the entire transfer space is used, will this function unmap the pages from the transfer virtual address. By having limited unmap calls, a lot of time spent flushing and unmapping is saved.
Parameters
page The page to zero.
threadContext The caller's thread info. It is used to determine which transfer virtual page to use.
Definition at line 608 of file user_thread.c.
{
    PVOID zeroVA;
    ULONG64 frameNumber;
    zeroVA = getThreadMapping(threadContext);
    frameNumber = getFrameNumber(page);
    if (MapUserPhysicalPages(zeroVA, 1, &frameNumber) == FALSE) {
        DebugBreak();
        printf("full_virtual_memory_test : could not map VA %p to page %llX\n", zeroVA, frameNumber);
        return FALSE;
    }
    memset(zeroVA, 0, PAGE_SIZE);
    freeThreadMapping(threadContext);
    return TRUE;
}
References freeThreadMapping(), getFrameNumber(), getThreadMapping(), PAGE_SIZE, and PTHREAD_INFO.
Referenced by freeVa(), mapPageFromFreeList(), and mapPageFromStandByList().