Virtual Memory Manager: include/threads/user_free.h File Reference
user_free.h File Reference
#include "variables/structures.h"
Functions
BOOL freeVa (PULONG64 arbitrary_va, PTHREAD_INFO threadInfo)
VOID unmapActivePage (pte *currentPTE, PTHREAD_INFO threadInfo, pfn *page)
BOOL unmapRescuePage (pte *currentPTE, PTHREAD_INFO threadInfo, pfn *page, boolean *addToFreeList)
BOOL unmapDiskFormatPTE (pte *currentPTE, PTHREAD_INFO threadInfo)
Function Documentation
freeVa()
BOOL freeVa (PULONG64 arbitrary_va, PTHREAD_INFO threadInfo)
Definition at line 17 of file user_free.c.
{
    pte* currentPTE;
    PTE_REGION* region;
    PCRITICAL_SECTION currentPageTableLock;
    boolean wasOnPage;
    pfn* page;
    ULONG64 freeListIndex;
    if (isVaValid((ULONG64) arbitrary_va) == FALSE) {
        DebugBreak();
    }
    currentPTE = va_to_pte((ULONG64) arbitrary_va);
    region = getPTERegion(currentPTE);
    currentPageTableLock = &region->lock;
    EnterCriticalSection(currentPageTableLock);
    if (currentPTE->validFormat.valid == 1) {
        unmapActivePage(currentPTE, threadInfo, page);
        wasOnPage = TRUE;
    } else if (isRescue(currentPTE)) {
        // sets wasOnPage
      if (unmapRescuePage(currentPTE, threadInfo, page, &wasOnPage) == REDO_FREE) {
          return REDO_FREE;
      }
    } else {
        unmapDiskFormatPTE(currentPTE, threadInfo);
        wasOnPage = FALSE;
    }
    if (wasOnPage) {
        zeroOnePage(page, threadInfo);
        freeListIndex = InterlockedIncrement(&freeListAddIndex);
        freeListIndex %= NUMBER_OF_FREE_LISTS;
        addPageToTail(&headFreeLists[freeListIndex], page, threadInfo);
        leavePageLock(page, threadInfo);
        InterlockedIncrement(&freeListLength);
    }
    currentPTE->entireFormat = EMPTY_PTE;
    return !REDO_FREE;
}
References addPageToTail(), EMPTY_PTE, pte::entireFormat, freeListAddIndex, freeListLength, getPTERegion(), headFreeLists, isRescue(), isVaValid(), leavePageLock(), PTE_REGION::lock, NUMBER_OF_FREE_LISTS, PTHREAD_INFO, REDO_FREE, unmapActivePage(), unmapDiskFormatPTE(), unmapRescuePage(), va_to_pte(), validPte::valid, pte::validFormat, and zeroOnePage().
unmapActivePage()
VOID unmapActivePage (pte * currentPTE, PTHREAD_INFO threadInfo, pfn * page)
Definition at line 73 of file user_free.c.
{
    PVOID va;
    ULONG64 frameNumber;
    va = pte_to_va(currentPTE);
    frameNumber = currentPTE->validFormat.frameNumber;
    page = getPFNfromFrameNumber(frameNumber);
    enterPageLock(page, threadInfo);
    removeFromMiddleOfList(&headActiveList, page, threadInfo);
    if (MapUserPhysicalPages(va, 1, NULL) == FALSE) {
        DebugBreak();
        printf("full_virtual_memory_test : could not map VA %p to page %llX\n", va, frameNumber);
        return;
    }
    return;
}
References enterPageLock(), validPte::frameNumber, getPFNfromFrameNumber(), headActiveList, pte_to_va(), PTHREAD_INFO, removeFromMiddleOfList(), and pte::validFormat.
Referenced by freeVa().
unmapDiskFormatPTE()
BOOL unmapDiskFormatPTE (pte * currentPTE, PTHREAD_INFO threadInfo)
Definition at line 158 of file user_free.c.
{
    set_disk_space_free(currentPTE->invalidFormat.diskIndex);
}
References invalidPte::diskIndex, pte::invalidFormat, PTHREAD_INFO, and set_disk_space_free().
Referenced by freeVa().
unmapRescuePage()
BOOL unmapRescuePage (pte * currentPTE, PTHREAD_INFO threadInfo, pfn * page, boolean * addToFreeList)
Definition at line 98 of file user_free.c.
{
    ULONG64 frameNumber;
    pte entryContents;
    entryContents.entireFormat = ReadULong64NoFence((ULONG64)currentPTE);
    if ((entryContents.transitionFormat.contentsLocation != MODIFIED_LIST)  &&
        (entryContents.transitionFormat.contentsLocation != STAND_BY_LIST )) {
        return REDO_FREE;
    }
    frameNumber = entryContents.transitionFormat.frameNumber;
    page = getPFNfromFrameNumber(frameNumber);
    if (page->pte->entireFormat != entryContents.entireFormat) {
        return REDO_FREE;
    }
    enterPageLock(page, threadInfo);
    if (page->pte != currentPTE) {
        leavePageLock(page, threadInfo);
        return REDO_FREE;
    }
    if ((currentPTE->transitionFormat.contentsLocation != MODIFIED_LIST)  &&
        (currentPTE->transitionFormat.contentsLocation != STAND_BY_LIST )) {
        leavePageLock(page, threadInfo);
        return REDO_FREE;
    }
    ASSERT(currentPTE->transitionFormat.frameNumber == frameNumber);
    //if there is a write in progress
    if (page->isBeingWritten == TRUE) {
        page->isBeingWritten = FALSE;
        page->isBeingFreed = TRUE;
        leavePageLock(page, threadInfo);
        *addToFreeList = FALSE;
    }
    else if (currentPTE->transitionFormat.contentsLocation == STAND_BY_LIST) {
        removeFromMiddleOfList(&headStandByList, page, threadInfo);
        set_disk_space_free(page->diskIndex);
        *addToFreeList = TRUE;
    } else {
        removeFromMiddleOfList(&headModifiedList,page, threadInfo);
        *addToFreeList = TRUE;
    }
    return !REDO_FREE;
}
References ASSERT, transitionPte::contentsLocation, pfn::diskIndex, enterPageLock(), pte::entireFormat, transitionPte::frameNumber, getPFNfromFrameNumber(), headModifiedList, headStandByList, pfn::isBeingFreed, pfn::isBeingWritten, leavePageLock(), MODIFIED_LIST, pfn::pte, PTHREAD_INFO, REDO_FREE, removeFromMiddleOfList(), set_disk_space_free(), STAND_BY_LIST, and pte::transitionFormat.
Referenced by freeVa().