Virtual Memory Manager: include/threads/zero_thread.h File Reference
zero_thread.h File Reference
#include "../variables/structures.h"
Functions
DWORD zeroingThread (LPVOID threadContext)
BOOL zeroMultiplePages (PULONG64 frameNumbers, ULONG64 batchSize)
Function Documentation
zeroingThread()
DWORD zeroingThread (LPVOID threadContext)
Definition at line 17 of file zero_thread.c.
{
    PTHREAD_INFO thread_info;
    pfn* page[BATCH_SIZE];
    ULONG64 frameNumbers[BATCH_SIZE];
    thread_info = (PTHREAD_INFO) threadContext;
    HANDLE* events[2];
    DWORD returnEvent;
    events[0] = zeroingStartEvent;
    events[1] = systemShutdownEvent;
    while (TRUE) {
        returnEvent = WaitForMultipleObjects(2,events, FALSE, INFINITE);
        //if the system shutdown event was signaled, exit
        if (returnEvent - WAIT_OBJECT_0 == 1) {
            return 0;
        }
        // //nptodo If you ever expand to more threads of this type, there is a race condition where batch size could change
        // for (int i = 0; i < BATCH_SIZE; ++i) {
        //     acquireLock(&lockToBeZeroedList);
        //     page[i] = container_of(RemoveHeadList(&headToBeZeroedList), pfn, entry);
        //     releaseLock(&lockToBeZeroedList);
        //     frameNumbers[i] = getFrameNumber(page[i]);
        // }
        zeroMultiplePages(frameNumbers, BATCH_SIZE);
        // acquire_srw_exclusive(&headFreeList.sharedLock, thread_info);
        // for (int i = 0; i < BATCH_SIZE; ++i) {
        //     InsertTailList(&headFreeList, &page[i]->entry);
        // }
        // release_srw_exclusive(&headFreeList.sharedLock);
    }
}
References BATCH_SIZE, PTHREAD_INFO, systemShutdownEvent, zeroingStartEvent, and zeroMultiplePages().
Referenced by createThreads().
zeroMultiplePages()
BOOL zeroMultiplePages (PULONG64 frameNumbers, ULONG64 batchSize)
Definition at line 61 of file zero_thread.c.
{
    if (MapUserPhysicalPages(zeroThreadTransferVa, batchSize, frameNumbers) == FALSE) {
        DebugBreak();
        printf("full_virtual_memory_test : could not map VA %p to page %llX\n", zeroThreadTransferVa, frameNumbers[0]);
        return FALSE;
    }
    memset(zeroThreadTransferVa, 0, PAGE_SIZE);
    if (MapUserPhysicalPages(zeroThreadTransferVa, batchSize, NULL) == FALSE) {
        DebugBreak();
        printf("full_virtual_memory_test : could not map VA %p to page %llX\n",  zeroThreadTransferVa, frameNumbers[0]);
        return FALSE;
    }
    return TRUE;
}
References PAGE_SIZE, and zeroThreadTransferVa.
Referenced by zeroingThread().